export const COOKIE_NAME = "app_session_id";
export const ONE_YEAR_MS = 1000 * 60 * 60 * 24 * 365;
export const AXIOS_TIMEOUT_MS = 30_000;
export const UNAUTHED_ERR_MSG = 'Please login (10001)';
export const NOT_ADMIN_ERR_MSG = 'You do not have required permission (10002)';

export const TOOLS = [
  // Implemented Tools
  {
    id: "merge-pdf",
    name: "Merge PDF",
    slug: "merge-pdf",
    category: "combine",
    shortDescription: "Combine multiple PDF files into a single document",
    fullDescription: "Merge multiple PDF files into one seamlessly. Reorder pages before combining.",
    icon: "Merge2",
    supportedInputs: ["PDF"],
    output: "PDF",
    implemented: true,
    order: 1,
  },
  {
    id: "split-pdf",
    name: "Split PDF",
    slug: "split-pdf",
    category: "organize",
    shortDescription: "Split a PDF into separate files or extract specific pages",
    fullDescription: "Divide a PDF into multiple files or extract individual pages.",
    icon: "Scissors",
    supportedInputs: ["PDF"],
    output: "PDF",
    implemented: true,
    order: 2,
  },
  {
    id: "compress-pdf",
    name: "Compress PDF",
    slug: "compress-pdf",
    category: "optimize",
    shortDescription: "Reduce PDF file size while maintaining quality",
    fullDescription: "Compress PDF files to reduce file size for easier sharing and storage.",
    icon: "Zap",
    supportedInputs: ["PDF"],
    output: "PDF",
    implemented: true,
    order: 3,
  },
  {
    id: "images-to-pdf",
    name: "Images to PDF",
    slug: "images-to-pdf",
    category: "convert",
    shortDescription: "Convert JPG, PNG, and other images to PDF",
    fullDescription: "Transform image files into professional PDF documents.",
    icon: "Image",
    supportedInputs: ["JPG", "PNG", "GIF", "BMP"],
    output: "PDF",
    implemented: true,
    order: 4,
  },
  {
    id: "pdf-to-images",
    name: "PDF to Images",
    slug: "pdf-to-images",
    category: "convert",
    shortDescription: "Convert PDF pages to individual image files",
    fullDescription: "Extract each page of a PDF as a separate image file (PNG or JPG).",
    icon: "FileImage",
    supportedInputs: ["PDF"],
    output: "PNG/JPG",
    implemented: true,
    order: 5,
  },
  {
    id: "extract-pages",
    name: "Extract Pages",
    slug: "extract-pages",
    category: "organize",
    shortDescription: "Extract specific pages from a PDF",
    fullDescription: "Select and extract specific pages from a PDF to create a new document.",
    icon: "FileText",
    supportedInputs: ["PDF"],
    output: "PDF",
    implemented: true,
    order: 6,
  },
  {
    id: "rotate-pages",
    name: "Rotate Pages",
    slug: "rotate-pages",
    category: "organize",
    shortDescription: "Rotate PDF pages 90, 180, or 270 degrees",
    fullDescription: "Rotate pages in your PDF document to the correct orientation.",
    icon: "RotateCw",
    supportedInputs: ["PDF"],
    output: "PDF",
    implemented: true,
    order: 7,
  },
  {
    id: "add-page-numbers",
    name: "Add Page Numbers",
    slug: "add-page-numbers",
    category: "organize",
    shortDescription: "Add page numbers to your PDF document",
    fullDescription: "Automatically add page numbers to all pages of your PDF.",
    icon: "Hash",
    supportedInputs: ["PDF"],
    output: "PDF",
    implemented: true,
    order: 8,
  },
  // All Tools Now Implemented
  {
    id: "edit-pdf",
    name: "Edit PDF",
    slug: "edit-pdf",
    category: "edit",
    shortDescription: "Edit text and images in PDF files",
    fullDescription: "Modify text, images, and formatting in your PDF documents.",
    icon: "Edit",
    supportedInputs: ["PDF"],
    output: "PDF",
    implemented: true,
    order: 9,
  },
  {
    id: "sign-pdf",
    name: "Sign PDF",
    slug: "sign-pdf",
    category: "security",
    shortDescription: "Add digital signatures to PDF documents",
    fullDescription: "Sign PDF files digitally with your signature.",
    icon: "Pen",
    supportedInputs: ["PDF"],
    output: "PDF",
    implemented: true,
    order: 10,
  },
  {
    id: "pdf-converter",
    name: "PDF Converter",
    slug: "pdf-converter",
    category: "convert",
    shortDescription: "Convert PDF to Word, Excel, PowerPoint, and more",
    fullDescription: "Convert PDF files to various document formats.",
    icon: "FileType2",
    supportedInputs: ["PDF"],
    output: "DOCX/XLSX/PPTX",
    implemented: true,
    order: 11,
  },
  {
    id: "extract-images",
    name: "Extract Images",
    slug: "extract-images",
    category: "organize",
    shortDescription: "Extract all images from a PDF file",
    fullDescription: "Pull all embedded images out of your PDF document.",
    icon: "ImagePlus",
    supportedInputs: ["PDF"],
    output: "PNG/JPG",
    implemented: true,
    order: 12,
  },
  {
    id: "protect-pdf",
    name: "Protect PDF",
    slug: "protect-pdf",
    category: "security",
    shortDescription: "Add password protection to PDF files",
    fullDescription: "Secure your PDF with password protection and permissions.",
    icon: "Lock",
    supportedInputs: ["PDF"],
    output: "PDF",
    implemented: true,
    order: 13,
  },
  {
    id: "unlock-pdf",
    name: "Unlock PDF",
    slug: "unlock-pdf",
    category: "security",
    shortDescription: "Remove password protection from PDF files",
    fullDescription: "Unlock password-protected PDF documents.",
    icon: "Unlock",
    supportedInputs: ["PDF"],
    output: "PDF",
    implemented: true,
    order: 14,
  },
  {
    id: "remove-pages",
    name: "Remove Pages",
    slug: "remove-pages",
    category: "organize",
    shortDescription: "Delete specific pages from a PDF",
    fullDescription: "Remove unwanted pages from your PDF document.",
    icon: "Trash2",
    supportedInputs: ["PDF"],
    output: "PDF",
    implemented: true,
    order: 15,
  },
  {
    id: "rearrange-pages",
    name: "Rearrange Pages",
    slug: "rearrange-pages",
    category: "organize",
    shortDescription: "Reorder pages in your PDF document",
    fullDescription: "Change the order of pages in your PDF.",
    icon: "Layers",
    supportedInputs: ["PDF"],
    output: "PDF",
    implemented: true,
    order: 16,
  },
  {
    id: "webpage-to-pdf",
    name: "Webpage to PDF",
    slug: "webpage-to-pdf",
    category: "convert",
    shortDescription: "Convert web pages to PDF documents",
    fullDescription: "Save web pages as PDF files.",
    icon: "Globe",
    supportedInputs: ["URL"],
    output: "PDF",
    implemented: true,
    order: 17,
  },
  {
    id: "pdf-ocr",
    name: "PDF OCR",
    slug: "pdf-ocr",
    category: "optimize",
    shortDescription: "Make scanned PDFs searchable with OCR",
    fullDescription: "Extract text from scanned PDFs using optical character recognition.",
    icon: "Search",
    supportedInputs: ["PDF"],
    output: "PDF",
    implemented: true,
    order: 18,
  },
  {
    id: "add-watermark",
    name: "Add Watermark",
    slug: "add-watermark",
    category: "edit",
    shortDescription: "Add text or image watermarks to PDF pages",
    fullDescription: "Protect your PDF with visible or invisible watermarks.",
    icon: "Droplet",
    supportedInputs: ["PDF"],
    output: "PDF",
    implemented: true,
    order: 19,
  },
  {
    id: "pdf-overlay",
    name: "PDF Overlay",
    slug: "pdf-overlay",
    category: "combine",
    shortDescription: "Overlay one PDF on top of another",
    fullDescription: "Combine PDFs by overlaying them on top of each other.",
    icon: "Layers2",
    supportedInputs: ["PDF"],
    output: "PDF",
    implemented: true,
    order: 20,
  },
  {
    id: "compare-pdfs",
    name: "Compare PDFs",
    slug: "compare-pdfs",
    category: "organize",
    shortDescription: "Compare two PDF files and highlight differences",
    fullDescription: "Find and visualize differences between two PDF documents.",
    icon: "GitCompare",
    supportedInputs: ["PDF"],
    output: "PDF",
    implemented: true,
    order: 21,
  },
  {
    id: "web-optimize",
    name: "Web Optimize",
    slug: "web-optimize",
    category: "optimize",
    shortDescription: "Optimize PDF files for web viewing",
    fullDescription: "Linearize and optimize PDFs for faster web viewing.",
    icon: "Zap",
    supportedInputs: ["PDF"],
    output: "PDF",
    implemented: true,
    order: 22,
  },
  {
    id: "redact-pdf",
    name: "Redact PDF",
    slug: "redact-pdf",
    category: "security",
    shortDescription: "Redact sensitive information from PDFs",
    fullDescription: "Permanently hide sensitive content in your PDF documents.",
    icon: "Eye",
    supportedInputs: ["PDF"],
    output: "PDF",
    implemented: true,
    order: 23,
  },
  {
    id: "create-pdf",
    name: "Create PDF",
    slug: "create-pdf",
    category: "convert",
    shortDescription: "Create PDF from text or documents",
    fullDescription: "Generate PDF files from text content or other documents.",
    icon: "Plus",
    supportedInputs: ["TXT", "DOC"],
    output: "PDF",
    implemented: true,
    order: 24,
  },
];

export const CATEGORIES = [
  {
    id: "combine",
    name: "Combine",
    slug: "combine",
    description: "Merge and combine multiple PDFs",
    icon: "Merge2",
  },
  {
    id: "organize",
    name: "Organize",
    slug: "organize",
    description: "Reorder, extract, and manage pages",
    icon: "Layers",
  },
  {
    id: "optimize",
    name: "Optimize",
    slug: "optimize",
    description: "Compress and improve PDF files",
    icon: "Zap",
  },
  {
    id: "convert",
    name: "Convert",
    slug: "convert",
    description: "Convert between PDF and other formats",
    icon: "FileType2",
  },
  {
    id: "edit",
    name: "Edit",
    slug: "edit",
    description: "Edit content and add elements",
    icon: "Edit",
  },
  {
    id: "security",
    name: "Security",
    slug: "security",
    description: "Protect and secure your PDFs",
    icon: "Lock",
  },
];

export const MAX_FILE_SIZE = 100 * 1024 * 1024; // 100MB
export const MAX_FILES = 50;
export const SUPPORTED_IMAGE_FORMATS = ["image/jpeg", "image/png", "image/gif", "image/bmp"];
export const SUPPORTED_PDF_FORMAT = "application/pdf";
